POST http://localhost:5000/task
Content-Type: application/json

{
  "task_id": "007measureall",
  "task_class": "PBR_measure_all",
  "device_id": "007",
  "sleep_period": 7,
  "lower_tol": 5,
  "upper_tol": 5,
  "od_channel": 1,
  "tolerance": 5,
  "ft_channel": 1,
  "max_outliers": 5,
  "pump_id": 1,

  "pump_config": {
      "task_id": "taskPBRpump",
      "task_class": "PSI_PBR_pump",
      "device_id": "007",
      "max_od": 0.3,
      "min_od": 0.2,
      "pump_id": 1
  }
}

###
