POST http://localhost:5000/task
Content-Type: application/json

{
  "task_id": "pump001",
  "task_class": "PSI_PBR_pump",
  "device_id": "001",
  "max_od": 0.38,
  "min_od": 0.36,
  "pump_id": 1,
  "od_task_id": "od001"
}

###