"""empty message

Revision ID: a930c1c16e47
Revises: 
Create Date: 2021-03-26 16:21:54.819275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a930c1c16e47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'response',
                    existing_type=mysql.VARCHAR(length=100),
                    type_=sa.String(length=1023),
                    existing_nullable=False)
    op.alter_column('events', 'time',
                    existing_type=mysql.DATETIME(fsp=3),
                    type_=mysql.DATETIME(fsp=6),
                    existing_nullable=False)
    op.alter_column('experiments', 'end',
                    existing_type=mysql.DATETIME(fsp=3),
                    type_=mysql.DATETIME(fsp=6),
                    existing_nullable=True)
    op.alter_column('experiments', 'start',
                    existing_type=mysql.DATETIME(fsp=3),
                    type_=mysql.DATETIME(fsp=6),
                    existing_nullable=False)
    op.alter_column('values', 'time',
                    existing_type=mysql.DATETIME(fsp=3),
                    type_=mysql.DATETIME(fsp=6),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('values', 'time',
                    existing_type=mysql.DATETIME(fsp=6),
                    type_=mysql.DATETIME(fsp=3),
                    existing_nullable=False)
    op.alter_column('experiments', 'start',
                    existing_type=mysql.DATETIME(fsp=6),
                    type_=mysql.DATETIME(fsp=3),
                    existing_nullable=False)
    op.alter_column('experiments', 'end',
                    existing_type=mysql.DATETIME(fsp=6),
                    type_=mysql.DATETIME(fsp=3),
                    existing_nullable=True)
    op.alter_column('events', 'time',
                    existing_type=mysql.DATETIME(fsp=6),
                    type_=mysql.DATETIME(fsp=3),
                    existing_nullable=False)
    op.alter_column('events', 'response',
                    existing_type=sa.String(length=1023),
                    type_=mysql.VARCHAR(length=100),
                    existing_nullable=False)
    # ### end Alembic commands ###
