"""empty message

Revision ID: bc7a92ac0ebe
Revises: a930c1c16e47
Create Date: 2021-04-01 09:25:13.576144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc7a92ac0ebe'
down_revision = 'a930c1c16e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'args',
                    existing_type=mysql.VARCHAR(length=100),
                    type_=sa.String(length=200),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'args',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=100),
                    existing_nullable=False)
    # ### end Alembic commands ###
