EVENT_TYPES = [
    (1, 'command executed'),
    (2, 'measurement not successful')
    ]

VARIABLES = [
    ('temp', 'current temperature', 'measured'),
    ('temp_min', 'max allowed temperature', 'measured'),
    ('temp_max', 'min allowed temperature', 'measured'),
    ('temp_on', 'thermoregulation on', 'measured'),
    ('pH', 'current pH', 'measured'),
    ('od', 'optical density', 'measured'),
    ('pump_direction', 'direction of pump', 'measured'),
    ('pump_on', 'pump turned on', 'measured'),
    ('pump_valves', 'pump valves settings', 'measured'),
    ('pump_flow', 'pump current flow', 'measured'),
    ('pump_min', 'pump min allowed flow', 'measured'),
    ('pump_max', 'pump max allowed flow', 'measured'),
    ('light_intensity', 'current light intensity', 'measured'),
    ('light_max', 'max allowed light intensity', 'measured'),
    ('light_on', 'light turned on', 'measured'),
    ('pwm_pulse', 'current stirring', 'measured'),
    ('pwm_min', 'minimal stirring', 'measured'),
    ('pwm_max', 'maximal stirring', 'measured'),
    ('pwm_on', 'stirring is turned on', 'measured'),
    ('o2', 'concentration of dissociated O2', 'measured'),
    ('ft_flash', 'steady-state terminal fluorescence', 'measured'),
    ('ft_background', 'steady-state terminal fluorescence background signal', 'measured'),
    ('qy', 'quantum yield', 'computed'),
    ('fm-flash', 'steady-state terminal fluorescence', 'measured'),
    ('fm-background', 'maximal fluorescence background signal', 'measured'),
    ('delay-cycles', 'number of cycles before reaching stable signal', 'measured'),
    ('co2', 'dissolved CO2 concentration', 'measured'),
    ('valve_flow_current', 'current valve flow', 'measured'),
    ('valve_flow_set', 'current valve flow target', 'measured'),
    ('warning', 'valve flow warning', 'measured'),
    ('valve_max_flow', 'valve max flow', 'measured'),
    ('valve_gas_type', 'valve gas type', 'measured'),
    ('user_gas_type', '???', 'measured'),
    ('co2-air', 'CO2 in air', 'measured'),
    ('small-valves', 'settings of individual vents', 'measured'),
    ('flow', 'flow from GAS to PBR', 'measured'),
    ('flow-target', 'target flow from GAS to PBR', 'measured'),
    ('flow-max', 'max allowed flow from GAS to PBR', 'measured'),
    ('pressure', 'current pressure', 'measured'),
    ('aux', 'AUX auxiliary input voltage', 'measured'),
    ('HWaddress', 'the MAC address of the PBR', 'measured'),
    ('clusterName', 'name of the bioreactor array', 'measured'),
    ('humidity', 'sensor humidity', 'measured'),
    ('vis', 'sensor illuminance', 'measured'),
    ('weight', 'measured weight', 'measured')
]
