name: Python package

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup mySQL database
      run: sudo -E env "PATH=$PATH" scripts/setup_runner.sh "user" "password"
    - name: Install libmysqlclient-dev
      run: sudo apt-get install -y libmysqlclient-dev
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        tests/run_tests.sh
